FROM bionexo/ruby:2.5.7_u20.04_p6.0.12

ENV RAILS_ENV production
ENV NODE_ENV production
ENV NOKOGIRI_USE_SYSTEM_LIBRARIES 1

RUN apt-get update && \
    apt-get -y dist-upgrade && \
    apt-get install -y postgresql-client && \
    curl -sL https://deb.nodesource.com/setup_12.x | bash && \
    apt-get install -y nodejs && \
    apt-get -y clean && \
    find /var/lib/apt/lists/ -type f -exec rm -f {} \;

RUN npm set registry http://npm.internal.dev.cloud.bionexo.com.br:4873/

# Creates Application root
RUN mkdir -p /bionexo-web
WORKDIR /bionexo-web

# Copy .sh, nginx, ssl files
COPY container/ /
RUN bash /bionexo/update-ca-certificates.sh

# To Gemfile install bio_audit gem, we need to Copy lib/bio_audit
COPY lib/bio_audit /bionexo-web/lib/bio_audit

# Copy lib files to third party folder
COPY lib/ /bionexo-web/vendor/

# Ensure gems are cached and only get updated when they change
COPY Gemfile Gemfile.lock ./
RUN ["/bin/bash", "-c", "bundle check &> /dev/null || bundle install --deployment --binstubs --without test:development"]

# Copy aplication code from work station
COPY . /bionexo-web

# Build the assets
RUN bundle exec rake i18n:js:export assets:precompile
RUN rm -rf log/* test/* tmp/cache/* tmp/pids/* tmp/sessions/* tmp/sockets/*

# Nginx requires this for graceful shutdown.
STOPSIGNAL SIGQUIT
